#!/bin/bash
#==
#   NOTE      - syncp
#   Author    - Chae Lee-Jin
#
#   Created   - 2024.02.19
#   Github    - https://github.com/aruyu
#   Contact   - vine9151@gmail.com
#/



function error_exit()
{
  echo "[ERROR] $1"
  exit 1
}




#==
#   Starting codes in blew
#/

if [[ $EUID -ne 0 ]]; then
  error_exit "This script must be run as ROOT!"
fi


case "$1" in
  --poweroff | -p )
    sync; sync; sync; sync;
    sync; sync; sync; sync;

    poweroff
    ;;

  --reboot )
    sync; sync; sync; sync;
    sync; sync; sync; sync;

    reboot
    ;;

  --help | * )
    echo "syncp [OPTIONS...]"
    echo
    echo "sync and control power of the system."
    echo
    echo "Options:"
    echo "     --help      Show this help"
    echo "  -p --poweroff  Switch off the machine"
    echo "     --reboot    Reboot the machine"
    echo
    ;;
esac
